"""Qdrant vector store for the Phase 2 retrieval layer."""

from __future__ import annotations

import math
import uuid
from dataclasses import asdict
from typing import Any, Sequence

from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    FieldCondition,
    Filter,
    MatchValue,
    PointStruct,
    VectorParams,
)

from src.document.models import BoundingBox
from src.retrieval.models import DocumentChunk, RetrievalResult


class QdrantVectorStore:
    """Store and retrieve DocumentChunk objects in Qdrant.

    The vector store is intentionally independent of the embedding
    provider. Embeddings are generated by the embedding layer and
    passed to this class for indexing.
    """

    def __init__(
        self,
        collection_name: str = "research_chunks",
        vector_size: int = 1024,
        distance: Distance = Distance.COSINE,
        client: QdrantClient | None = None,
        path: str | None = None,
        url: str | None = None,
        api_key: str | None = None,
    ) -> None:
        if not collection_name.strip():
            raise ValueError("collection_name must not be empty")

        if vector_size <= 0:
            raise ValueError("vector_size must be greater than 0")

        if client is not None and any(
            value is not None for value in (path, url, api_key)
        ):
            raise ValueError(
                "client cannot be combined with path, url, or api_key"
            )

        self.collection_name = collection_name
        self.vector_size = vector_size
        self.distance = distance

        self.client = self._create_client(
            client=client,
            path=path,
            url=url,
            api_key=api_key,
        )

        self._ensure_collection()

    @staticmethod
    def _create_client(
        client: QdrantClient | None,
        path: str | None,
        url: str | None,
        api_key: str | None,
    ) -> QdrantClient:
        """Create or reuse a Qdrant client."""

        if client is not None:
            return client

        if url is not None:
            return QdrantClient(
                url=url,
                api_key=api_key,
            )

        if path is not None:
            return QdrantClient(path=path)

        return QdrantClient(":memory:")

    def _ensure_collection(self) -> None:
        """Create the collection if it does not already exist."""

        if self.client.collection_exists(self.collection_name):
            existing = self.client.get_collection(
                self.collection_name
            )

            existing_size = existing.config.params.vectors.size

            if existing_size != self.vector_size:
                raise ValueError(
                    "Existing Qdrant collection has vector size "
                    f"{existing_size}, expected {self.vector_size}"
                )

            return

        self.client.create_collection(
            collection_name=self.collection_name,
            vectors_config=VectorParams(
                size=self.vector_size,
                distance=self.distance,
            ),
        )

    @staticmethod
    def _point_id(chunk_id: str) -> uuid.UUID:
        """Convert an application chunk ID into a deterministic UUID.

        Qdrant point IDs must be integers or UUIDs. The original
        application-level chunk ID is preserved separately in the
        payload, so provenance remains unchanged.
        """

        return uuid.uuid5(
            uuid.NAMESPACE_URL,
            chunk_id,
        )

    @staticmethod
    def _chunk_payload(chunk: DocumentChunk) -> dict[str, Any]:
        """Convert a DocumentChunk into a Qdrant payload."""

        return {
            "chunk_id": chunk.chunk_id,
            "document_id": chunk.document_id,
            "text": chunk.text,
            "page_numbers": list(chunk.page_numbers),
            "source": chunk.source,
            "section": chunk.section,
            "bounding_boxes": [
                asdict(bbox)
                for bbox in chunk.bounding_boxes
            ],
            "element_ids": list(chunk.element_ids),
            "metadata": chunk.metadata,
        }

    @staticmethod
    def _payload_to_chunk(
        payload: dict[str, Any],
    ) -> DocumentChunk:
        """Reconstruct a DocumentChunk from a Qdrant payload."""

        bounding_boxes = tuple(
            BoundingBox(**bbox)
            for bbox in payload.get("bounding_boxes", [])
        )

        return DocumentChunk(
            chunk_id=payload["chunk_id"],
            document_id=payload["document_id"],
            text=payload["text"],
            page_numbers=tuple(payload["page_numbers"]),
            source=payload["source"],
            section=payload.get("section"),
            bounding_boxes=bounding_boxes,
            element_ids=tuple(
                payload.get("element_ids", [])
            ),
            metadata=payload.get("metadata", {}),
        )

    def upsert(
        self,
        chunks: Sequence[DocumentChunk],
        embeddings: Sequence[Sequence[float]],
    ) -> int:
        """Insert or update chunks and their embeddings."""

        if len(chunks) != len(embeddings):
            raise ValueError(
                "chunks and embeddings must have the same length"
            )

        if not chunks:
            return 0

        points: list[PointStruct] = []

        for chunk, embedding in zip(
            chunks,
            embeddings,
            strict=True,
        ):
            if len(embedding) != self.vector_size:
                raise ValueError(
                    f"Embedding for chunk {chunk.chunk_id} has "
                    f"dimension {len(embedding)}, "
                    f"expected {self.vector_size}"
                )

            if not all(
                math.isfinite(float(value))
                for value in embedding
            ):
                raise ValueError(
                    f"Embedding for chunk {chunk.chunk_id} "
                    "must contain only finite values"
                )

            points.append(
                PointStruct(
                    id=self._point_id(chunk.chunk_id),
                    vector=list(embedding),
                    payload=self._chunk_payload(chunk),
                )
            )

        self.client.upsert(
            collection_name=self.collection_name,
            points=points,
        )

        return len(points)

    def get(
        self,
        chunk_ids: Sequence[str],
    ) -> list[DocumentChunk]:
        """Retrieve chunks by their application-level chunk IDs."""

        if not chunk_ids:
            return []

        point_ids = [
            self._point_id(chunk_id)
            for chunk_id in chunk_ids
        ]

        records = self.client.retrieve(
            collection_name=self.collection_name,
            ids=point_ids,
            with_payload=True,
            with_vectors=False,
        )

        return [
            self._payload_to_chunk(record.payload or {})
            for record in records
        ]

    # ------------------------------------------------------------------
    # Phase 2.4: Dense Semantic Search
    # ------------------------------------------------------------------

    def search(
        self,
        query_vector: Sequence[float],
        top_k: int = 20,
    ) -> list[RetrievalResult]:
        """Perform dense semantic retrieval using cosine similarity."""

        if top_k < 1:
            raise ValueError("top_k must be >= 1")

        if len(query_vector) != self.vector_size:
            raise ValueError(
                f"Query vector dimension {len(query_vector)} "
                f"does not match vector size {self.vector_size}"
            )

        response = self.client.query_points(
            collection_name=self.collection_name,
            query=list(query_vector),
            limit=top_k,
            with_payload=True,
        )

        results: list[RetrievalResult] = []

        for rank, hit in enumerate(response.points, start=1):

            chunk = self._payload_to_chunk(hit.payload or {})

            results.append(
                RetrievalResult(
                    chunk=chunk,
                    score=float(hit.score),
                    rank=rank,
                    retrieval_method="dense",
                )
            )

        return results

    # ------------------------------------------------------------------
    # Utility Methods
    # ------------------------------------------------------------------

    def delete_document(self, document_id: str) -> None:
        """Delete every chunk belonging to a document."""

        if not document_id.strip():
            raise ValueError("document_id must not be empty")

        self.client.delete(
            collection_name=self.collection_name,
            points_selector=Filter(
                must=[
                    FieldCondition(
                        key="document_id",
                        match=MatchValue(value=document_id),
                    )
                ]
            ),
        )

    def count(self) -> int:
        """Return the number of stored chunks."""

        result = self.client.count(
            collection_name=self.collection_name,
            exact=True,
        )

        return result.count

    def clear(self) -> None:
        """Delete and recreate the collection."""

        if self.client.collection_exists(self.collection_name):
            self.client.delete_collection(
                self.collection_name
            )

        self._ensure_collection()