"""Phase 3.2 PageIndex Flash-backed vectorless retrieval adapter.

The PageIndex tree is built offline by PageIndex Flash and persisted as JSON.

This adapter:
    1. loads the persisted PageIndex tree,
    2. delegates query-time structural navigation to PageIndexNavigator,
    3. maps selected node page ranges onto existing DocumentChunk objects,
    4. returns the existing RetrievalResult contract.

No vector database, embeddings, BM25, ColBERT, or LLM calls are made
during this deterministic navigation stage.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

from src.document.models import Document
from src.retrieval.models import DocumentChunk, RetrievalResult
from src.retrieval.pageindex.navigator import PageIndexNavigator


@dataclass(frozen=True)
class PageIndexConfig:
    """Configuration for loading a persisted PageIndex Flash tree.

    ``index_path`` is optional.

    When omitted, the adapter derives the path from the document source path:

        .pageindex/<pdf-file-name>.json

    This matches the Phase 3.2 Flash artifact generated by:

        scripts/build_pageindex_flash.py
    """

    index_path: str | Path | None = None


class PageIndexRetriever:
    """Vectorless retrieval over a persisted PageIndex Flash tree.

    PageIndex Flash builds the structural tree offline.

    At query time this class:
        1. loads the persisted tree,
        2. navigates the tree using PageIndexNavigator,
        3. obtains candidate structural nodes,
        4. converts their page ranges into document chunks,
        5. returns RetrievalResult objects.

    The existing DocumentChunk and RetrievalResult contracts are preserved.
    """

    retrieval_method = "pageindex"

    def __init__(
        self,
        document: Document,
        chunks: Iterable[DocumentChunk],
        config: PageIndexConfig | None = None,
    ) -> None:
        if not document.source_path:
            raise ValueError("document.source_path must not be empty")

        self.document = document
        self._chunks = list(chunks)
        self.config = config or PageIndexConfig()

        self.structure = self._build_structure()

        self.navigator = PageIndexNavigator(
            self.structure
        )

    def _resolve_index_path(self) -> Path:
        """Resolve the persisted PageIndex JSON path."""

        if self.config.index_path is not None:
            return Path(self.config.index_path)

        source_path = Path(self.document.source_path)

        return (
            Path(".pageindex")
            / f"{source_path.stem}.json"
        )

    def _build_structure(self) -> dict[str, Any]:
        """Load and validate an existing PageIndex Flash JSON artifact.

        Despite the historical method name ``_build_structure``, this method
        intentionally does NOT build anything.

        It only loads the tree generated offline by PageIndex Flash.
        """

        index_path = self._resolve_index_path()

        if not index_path.exists():
            raise FileNotFoundError(
                "PageIndex index not found: "
                f"{index_path}. Build the Flash index first."
            )

        if not index_path.is_file():
            raise FileNotFoundError(
                "PageIndex index path is not a file: "
                f"{index_path}"
            )

        try:
            with index_path.open(
                "r",
                encoding="utf-8",
            ) as handle:
                result = json.load(handle)

        except json.JSONDecodeError as exc:
            raise ValueError(
                f"Invalid PageIndex JSON: {index_path}"
            ) from exc

        except OSError as exc:
            raise OSError(
                f"Unable to read PageIndex index: {index_path}"
            ) from exc

        if not isinstance(result, dict):
            raise ValueError(
                "PageIndex index must contain a JSON object: "
                f"{index_path}"
            )

        structure = result.get("structure")

        if not isinstance(structure, list) or not structure:
            raise RuntimeError(
                "PageIndex index contains no document structure: "
                f"{index_path}"
            )

        self._validate_structure(
            structure,
            index_path,
        )

        return result

    @classmethod
    def _validate_structure(
        cls,
        nodes: list[dict[str, Any]],
        index_path: Path,
    ) -> None:
        """Validate the structural fields required by retrieval."""

        for node in nodes:
            if not isinstance(node, dict):
                raise ValueError(
                    "Invalid PageIndex node in "
                    f"{index_path}: expected object"
                )

            for field in (
                "node_id",
                "title",
                "start_index",
                "end_index",
            ):
                if field not in node:
                    raise ValueError(
                        "PageIndex node is missing required field "
                        f"'{field}' in {index_path}"
                    )

            try:
                start = int(node["start_index"])
                end = int(node["end_index"])

            except (TypeError, ValueError) as exc:
                raise ValueError(
                    "Invalid page range for PageIndex node "
                    f"{node.get('node_id')!r} in {index_path}"
                ) from exc

            if start < 1 or end < start:
                raise ValueError(
                    "Invalid page range for PageIndex node "
                    f"{node.get('node_id')!r}: {start}-{end}"
                )

            children = node.get("nodes") or []

            if not isinstance(children, list):
                raise ValueError(
                    "Invalid children for PageIndex node "
                    f"{node.get('node_id')!r} in {index_path}"
                )

            cls._validate_structure(
                children,
                index_path,
            )

    def retrieve(
        self,
        query: str,
        top_k: int = 10,
    ) -> list[RetrievalResult]:
        """Retrieve document chunks using structural PageIndex navigation."""

        if not query or not query.strip():
            raise ValueError("query must not be empty")

        if top_k < 1:
            raise ValueError("top_k must be >= 1")

        navigation_candidates = self.navigator.navigate(
            query=query,
            top_k=top_k,
        )

        if not navigation_candidates:
            return []

        page_ranges = self._page_ranges_for_candidates(
            navigation_candidates
        )

        candidates = self._chunks_for_page_ranges(
            page_ranges
        )

        results: list[RetrievalResult] = []
        seen: set[str] = set()

        for chunk, candidate in candidates:
            if chunk.chunk_id in seen:
                continue

            seen.add(chunk.chunk_id)

            node = candidate.node

            metadata = dict(chunk.metadata)

            metadata.update(
                {
                    "retrieval_sources": [
                        self.retrieval_method
                    ],
                    "pageindex_node_id": node.get(
                        "node_id"
                    ),
                    "pageindex_title": node.get(
                        "title"
                    ),
                    "pageindex_start_index": node.get(
                        "start_index"
                    ),
                    "pageindex_end_index": node.get(
                        "end_index"
                    ),
                    "pageindex_navigation_score": (
                        candidate.score
                    ),
                    "pageindex_navigation_rank": (
                        candidate.rank
                    ),
                    "pageindex_node_path": list(
                        candidate.path
                    ),
                }
            )

            enriched_chunk = DocumentChunk(
                chunk_id=chunk.chunk_id,
                document_id=chunk.document_id,
                text=chunk.text,
                page_numbers=chunk.page_numbers,
                source=chunk.source,
                section=chunk.section,
                bounding_boxes=chunk.bounding_boxes,
                element_ids=chunk.element_ids,
                metadata=metadata,
            )

            results.append(
                RetrievalResult(
                    chunk=enriched_chunk,
                    score=candidate.score,
                    rank=len(results) + 1,
                    retrieval_method=self.retrieval_method,
                    metadata={
                        "pageindex_navigation_rank": (
                            candidate.rank
                        ),
                        "pageindex_navigation_score": (
                            candidate.score
                        ),
                        "pageindex_node_path": list(
                            candidate.path
                        ),
                    },
                )
            )

            if len(results) >= top_k:
                break

        return results

    @staticmethod
    def _page_ranges_for_candidates(
        candidates,
    ) -> list[tuple[int, int, Any]]:
        """Convert navigation candidates into validated page ranges."""

        ranges: list[
            tuple[int, int, Any]
        ] = []

        for candidate in candidates:
            node = candidate.node

            try:
                start = int(
                    node["start_index"]
                )

                end = int(
                    node.get(
                        "end_index"
                    ) or start
                )

            except (
                KeyError,
                TypeError,
                ValueError,
            ):
                continue

            if start < 1 or end < start:
                continue

            ranges.append(
                (
                    start,
                    end,
                    candidate,
                )
            )

        return ranges

    def _chunks_for_page_ranges(
        self,
        ranges,
    ) -> list[
        tuple[
            DocumentChunk,
            Any,
        ]
    ]:
        """Map PageIndex page ranges onto existing document chunks."""

        candidates: list[
            tuple[
                int,
                int,
                str,
                DocumentChunk,
                Any,
            ]
        ] = []

        for candidate_rank, (
            start,
            end,
            candidate,
        ) in enumerate(
            ranges,
            start=1,
        ):
            for chunk in self._chunks:
                if any(
                    start <= page <= end
                    for page in chunk.page_numbers
                ):
                    candidates.append(
                        (
                            candidate_rank,
                            chunk.primary_page,
                            chunk.chunk_id,
                            chunk,
                            candidate,
                        )
                    )

        candidates.sort(
            key=lambda item: (
                item[0],
                item[1],
                item[2],
            )
        )

        return [
            (chunk, candidate)
            for (
                _rank,
                _page,
                _chunk_id,
                chunk,
                candidate,
            ) in candidates
        ]


__all__ = [
    "PageIndexConfig",
    "PageIndexRetriever",
]